apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
---
{{- $namespace := .Release.Namespace }}
{{- range $dep := .Chart.Dependencies }}
{{- if not (has $dep.Name (list "yas-configuration" "database" "identity" "jaeger" "swagger-ui")) }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $dep.Name }}-retry-policy
  namespace: {{ $namespace }}
spec:
  host: {{ $dep.Name }}.{{ $namespace }}.svc.cluster.local
  trafficPolicy:
    retrying:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream
---
{{- end }}
{{- end }}



