apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: yas-mtls-policy
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
---
{{- $namespace := .Release.Namespace }}
{{- range $dep := .Chart.Dependencies }}
{{- if not (has $dep.Name (list "yas-configuration" "database" "identity" "jaeger" "swagger-ui")) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $dep.Name }}-retry-policy
  namespace: {{ $namespace }}
spec:
  hosts:
  - {{ $dep.Name }}
  http:
  - route:
    - destination:
        host: {{ $dep.Name }}
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream
---
{{- end }}
{{- end }}




