# Cấu hình Retry cho 'product' service (Namespace Dev)
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-retry
  namespace: dev
spec:
  hosts:
  - product.dev.svc.cluster.local
  http:
  - route:
    - destination:
        host: product.dev.svc.cluster.local
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure,refused-stream"
---
# Cấu hình Retry cho 'order' service (Namespace Dev)
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-retry
  namespace: dev
spec:
  hosts:
  - order.dev.svc.cluster.local
  http:
  - route:
    - destination:
        host: order.dev.svc.cluster.local
    retries:
      attempts: 3
      perTryTimeout: 3s
      retryOn: "5xx,connect-failure,refused-stream"
---
# Cấu hình Retry cho 'product' service (Namespace Staging)
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-retry
  namespace: staging
spec:
  hosts:
  - product.staging.svc.cluster.local
  http:
  - route:
    - destination:
        host: product.staging.svc.cluster.local
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure,refused-stream"
