# Main values file for yas-dev umbrella chart.
storefront-bff:
  backend:
    fullnameOverride: storefront-bff
    serviceAccount:
      create: true

backoffice-bff:
  backend:
    fullnameOverride: backoffice-bff
    serviceAccount:
      create: true

